# Generated by Django 5.2.6 on 2025-09-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="note",
            name="pinned",
            field=models.BooleanField(default=False),
        ),
    ]
