# Generated by Django 5.2.6 on 2025-09-11 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0002_alter_note_archived_alter_note_pinned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
